# Generated by Django 3.0.7 on 2020-06-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('common_name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('key', models.TextField(blank=True, verbose_name='Private key')),
                ('cert', models.TextField(blank=True, verbose_name='Public certificate')),
                ('usage', models.CharField(choices=[('R', 'Root CA'), ('D', 'Domain'), ('C', 'Client')], default='R', max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lacri.Authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
                'unique_together': {('user', 'slug'), ('user', 'common_name')},
            },
        ),
    ]
